{% set name = "strpdatetime" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/strpdatetime-{{ version }}.tar.gz
  sha256: 01b95a4841db31503f616b3ba545f0b548841598296b17000ba00fbe11e49264

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.13
    - textx >=4.0.1,<5.0.0

test:
  imports:
    - strpdatetime
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Parse strings into Python datetime objects; extends Python's datetime.strptime() with additional features.
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cofinoa
