{% set name = "github_release" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/github_release-{{ version }}.tar.gz
  sha256: 168148bd3c6737b242927f05cfe06bdafc4ff7b685f2913bdfd6881dd2175042

build:
  entry_points:
    - github_release = github_release:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - github3.py ==0.9

test:
  imports:
    - github_release
  commands:
    - pip check
    - github_release --help
  requires:
    - pip

about:
  home: http://dev.hubspot.com/
  summary: Release to GitHub
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cofinoa
