{% set name = "osxphotos" %}
{% set version = "0.67.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/osxphotos-{{ version }}.tar.gz
  sha256: f8a650a41bff5ec3feac86fc765ca610a728c31d70dfba3880cca9412a696d87

build:
  noarch: python
  entry_points:
    - osxphotos=osxphotos.__main__:cli_main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bitmath >=1.3
    - bpylist2 >=4.1.1
    - click 
    - mako >=1.2
    - more-itertools >=8.8
    - objexplore
    - packaging >=21.3
    - pathvalidate >=2.4
    - ptpython >=3.0
    - pytimeparse2
    - pyyaml >=6.0
    - requests >=2.27
    - rich-theme-manager
    - rich
    - shortuuid >=1.0
    - strpdatetime
    - tenacity >=8.0
    - textx >=4.0
    - toml >=0.10
    - wrapt >=1.14
    - wurlitzer >=3.0
    - xdg >=5.1

test:
  imports:
    - osxphotos
  commands:
    - pip check
    - osxphotos --help
  requires:
    - pip

about:
  home: https://github.com/RhetTbull/
  summary: Export photos from Apple's macOS Photos app and query the Photos library database to access metadata about images.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cofinoa
