{% set name = "osxphotos" %}
{% set version = "0.67.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/osxphotos-{{ version }}.tar.gz
  sha256: f8a650a41bff5ec3feac86fc765ca610a728c31d70dfba3880cca9412a696d87

build:
  noarch: python
  entry_points:
    - osxphotos=osxphotos.__main__:cli_main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bitmath >=1.3.3.1,<1.4.0.0
    - bpylist2 >=4.1.1,<5.0.0
    - click >=8.1.3,<9.0
    - mako >=1.2.2,<1.3.0
    - more-itertools >=8.8.0,<9.0.0
    - objexplore >=1.6.3,<2.0.0
    - packaging >=21.3
    - pathvalidate >=2.4.1,<4.0.0
    - ptpython >=3.0.20,<4.0.0
    - pytimeparse2 >=1.4.0,<2.0.0
    - pyyaml >=6.0.0,<7.0.0
    - requests >=2.27.1,<3.0.0
    - rich-theme-manager >=0.11.0
    - rich >=13.5.2,<14.0.0
    - shortuuid >=1.0.9,<2.0.0
    - strpdatetime >=0.3.0
    - tenacity >=8.0.1,<9.0.0
    - textx >=4.0.1,<5.0.0
    - toml >=0.10.2,<0.11.0
    - wrapt >=1.14.1,<2.0.0
    - wurlitzer >=3.0.2,<4.0.0
    - xdg >=5.1.1

test:
  imports:
    - osxphotos
  commands:
    - pip check
    - osxphotos --help
  requires:
    - pip

about:
  home: https://github.com/RhetTbull/
  summary: Export photos from Apple's macOS Photos app and query the Photos library database to access metadata about images.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cofinoa
