{% set name = "rich-theme-manager" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rich-theme-manager-{{ version }}.tar.gz
  sha256: 3bc1effa4b6c42f72994b73c8b3c391b1c6e803deccc2fc3932da31b00f1a112

build:
  entry_points:
    - rich_theme_manager = rich_theme_manager:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0.0
    - rich >=11.0

test:
  imports:
    - rich_theme_manager
  commands:
    - pip check
    - rich_theme_manager --help
  requires:
    - pip

about:
  home: https://github.com/RhetTbull/rich_theme_manager
  summary: Manage rich themes for CLI applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cofinoa
