{% set name = "pytimeparse2" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytimeparse2-{{ version }}.tar.gz
  sha256: 98668cdcba4890e1789e432e8ea0059ccf72402f13f5d52be15bdfaeb3a8b253

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - cython
    - github_release
    - csscompressor
    - jsmin
    - sphinx
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pytimeparse2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onegreyonewhite/pytimeparse2
  summary: Time expression parser.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cofinoa
